In [4]:
import torch
print(torch.__version__)

1.7.1+cu101


In [7]:
x = [[0,1,2], [3,4,5]]
t_x = torch.FloatTensor(x)
print(t_x)

tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [10]:
import numpy as np

x = np.arange(6).reshape((2,3))
t_x = torch.from_numpy(x)
print(t_x)
print(t_x.numpy())

tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)
[[0 1 2]
 [3 4 5]]


In [5]:
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.current_device())
print(torch.cuda.get_device_name(0))

True
1
0
Quadro P2000
